### ISSUE TITLE
BUG - Github OAuth Connection Failure

### ISSUE THREAD

**Issue by Flooflez** [AnubisLMS/Anubis#470]
**Describe the bug**
Attempting to link Github account to student anubis account yields an "Unable to set username" error message, despite successfully connecting with the OAuth App (wabscale). Subsequent attempts with the same Github account result in the same error message, but with no redirect to Github to sign in or connect to wabscale.

**To Reproduce**
1. Go to profile
2. Click LINK ACCOUNT WITH GITHUB button
3. Enter Github account information
4. Click Authorize wabscale
5. Receive Error

**Screenshots**
OAuth App is successfully given access.
<img width="1016" alt="image" src="https://github.com/AnubisLMS/Anubis/assets/97826110/5f3072cb-51bc-4ab5-ae7a-b3394a76d2fc">

Error appears as follows.
<img width="599" alt="image" src="https://github.com/AnubisLMS/Anubis/assets/97826110/9e69cf56-6ad1-492c-9e89-9ff8c655d068">

**Desktop (please complete the following information):**
 - OS: macOs Big Sur, Windows 11
 - Browser Firefox, Microsoft Edge
 

**Additional context**
Might be related to #469 

Web console yields the following errors:
``` 
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'run-ad-auction'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'join-ad-interest-group'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'browsing-topics'. 
```

Error is raised in the [auth.py script](https://github.com/AnubisLMS/Anubis/blob/e5ac3157dd3de4a633245ab9aa02b9ac23f88563/api/anubis/views/public/auth.py#L210)

Have tried different browsers, OS, and Github accounts.

**Comment by wabscale** [comment]
Hi @Flooflez can you join our discord and PM me? I cannot reproduce this, so I will need your help to see what the actual error is in prod.

https://discord.gg/Ggv6s7DN

**Comment by wabscale** [comment]
This would happen for users that didnt have a public email address on github. I pushed something to fix: 

https://github.com/AnubisLMS/Anubis/commit/fdb46f4ef6f7a06efaea856156353f8315dc2409

**Comment by GeJamesJin** [comment]
Hi @wabscale, @Flooflez's issue with "unable to set username" doesn't seem to be fixed for me. I am following exactly the same process of linking a Github account to Anubis, and I have been getting the identical error on Anubis's side.

Also, I have made my email address on Github public, which doesn't resolve the issue unfortunately.
<img width="457" alt="image" src="https://github.com/AnubisLMS/Anubis/assets/159092813/50654e5c-aa42-4fb4-82c5-9c8a445d0717">
<img width="1128" alt="image" src="https://github.com/AnubisLMS/Anubis/assets/159092813/94a4f274-e170-4f94-b6a0-92a27fbf5352">

**Comment by wabscale** [comment]
@GeJamesJin This is because of a different field for you being private on your github profile. I have updated things to handle it correctly:

https://github.com/AnubisLMS/Anubis/commit/abac58c153f5d22ab3e67ddd5a54e5dc85b8528e

You can try again.

**Comment by GeJamesJin** [comment]
Hi @wabscale, I was able to successfully link my profile to Anubis, thanks for the prompt fix.
